// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Todo.Backend.EFCore;

#nullable disable

namespace api.migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20221111203011_AddOwner")]
    partial class AddOwner
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence<int>("global_sequence");

            modelBuilder.Entity("Todo.Backend.EFCore.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR global_sequence");

                    b.Property<byte>("Completed")
                        .HasColumnType("tinyint")
                        .HasColumnName("completed");

                    b.Property<string>("Owner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("anonymous")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("todo");

                    b.HasKey("Id");

                    b.ToTable("todos");
                });
#pragma warning restore 612, 618
        }
    }
}
